export const All_PRODUCT_REQUEST ="All_PRODUCT_REQUEST";
export const All_PRODUCT_SUCCESS ="All_PRODUCT_SUCCESS";
export const All_PRODUCT_FALL ="All_PRODUCT_FALL";
export const CLEAR_ERRORS ="CLEAR_ERRORS";
